external init: int -> int -> unit = "console_init"
external free: unit -> unit = "console_free"
external should_quit: unit -> bool = "console_should_quit"
external render: unit -> unit = "console_render"
external set_fill_color: int -> int -> int -> unit = "console_set_fill_color"
external fill_rect: int -> int -> int -> int -> unit = "console_fill_rect"
external clear: int -> int -> int -> unit = "console_clear"
